### PR TITLE
Update to Python 3

### PR DESCRIPTION
**Pull request by qwertystop**
I've just gone through and updated this to Python 3 in prep. for my own project. Figured it was only polite to pass that back.

### CODE REVIEW

**Comment by billzorn** [comment]
This looks like a very useful patch. It's large, so I'm hesitant to just pull it and go without doing some of my own testing, but I was thinking about converting to python3 anyway. It's very nice to see that someone else has already done the hard work for me. :)

I was away for a few weeks, so I'm still busy catching up with a bunch of other things, but I'll put this on the stack.

I should really have a more robust testing methodology. I'm hesitant to do anything fancy like a unit testing framework, but if you have a standard suite of sanity tests (like making sure all of the formats run without crashing on the latest output.txt) that might be helpful.

Oh, and a word of warning about the way PRs work on github, if you're unfamiliar like I was---if you commit anything else to the branch you used to submit the request, it will be automatically added to the PR. So yeah, you may want to make a separate branch for your pokemon adaptation, or a separate fork, but then you'd have to transfer your python3 changes somehow if you want them before I deal with this pull request. I'm no expert.

**Comment by qwertystop** [comment]
I'm going to re-fork mine for the Pokemon adaptation if you don't get around to pulling this before I get around to starting said adaptation - I didn't know how that worked before, but caught it when I did the README fixes.

I did not test all formats - I don't know what they're supposed to look like ('doesn't crash' and 'works as intended' are two different things), and couldn't get Google's word-to-vector thing working anyway. I did test the default format and it looks fine.

I know there's a lot of changes, but they're pretty simple ones. The first commit is all the 2to3, which I'm pretty sure is guaranteed non-breaking and in this case is almost entirely just changing print to print(). The next two are that sorted() now takes a key instead of a comparator. After that it's just docs.

**Comment by qwertystop** [comment]
...Great. Turns out GitHub won't let me fork this while I've already got a fork of it, so it looks like my Pokemon adaptation will be a branch despite being different enough to justify being a fork.

**Comment by qwertystop** [comment]
Okay, I'm going to retract this and resubmit a pull request from an identical but non-master branch so I can actually work properly on my further progress. Sorry for the inconvenience.

**Pull request closed without merging**
